### ISSUE TITLE
Can't seem to get running... :(

### ISSUE THREAD

**Issue by Johnsalzarulo** [JoeRoddy/combust#2]
I thiiiiiiiink this is an npm issue on my machine but I am running other npm modules / packages whatever without issue - react native etc. 

However: I run: 

`npm i -g combust`

and I get: 
````
➜  ~ npm i -g combust
/Users/johnsalzarulo/.npm-packages/bin/combust -> /Users/johnsalzarulo/.npm-packages/lib/node_modules/combust/bin/combust.js
+ combust@1.0.17
updated 1 package in 8.455s
````
All seems good - 

Then I run

````
➜  ~ combust create myApp    
````

I get: 

````
zsh: command not found: combust
````

Even changing my shell to `bash` I get: 

````
bash: combust: command not found
````

As I said - It's probably some n00b NPM issue I don't understand. I'm a little more familar with YARN - 
 but even then this whole NPM thing is kind of lost on me. I'd love some direction to start playing with this thing. 

So sorry to bug you! Thanks for your time.

My system: 

````
ProductName:	Mac OS X
ProductVersion:	10.13.3
BuildVersion:	17D47
````

**Comment by JoeRoddy** [comment]
You might have to do `sudo npm i -g combust`

I always have to include `sudo` on Linux for -g installs, but I thought it wasn't necessary on mac.  What version of npm are you on?

**Comment by JoeRoddy** [comment]
It looks like it installed though from your output.. weird..

This is a hack, but you should be able to add an alias to your `.bashrc`, something like this:
`alias combust="/Users/johnsalzarulo/.npm-packages/lib/node_modules/combust/bin/combust.js"`

**Comment by Johnsalzarulo** [comment]
Heyo 👋
<img width="1098" alt="screen shot 2018-06-15 at 6 55 23 am" src="https://user-images.githubusercontent.com/3476109/41471662-200bea12-7069-11e8-817c-ef330a6df07d.png">

I've got issues generally with my npm permissions and modules... don't think it's this libraries fault. 

Thaaaaaaanks
